### ISSUE TITLE
is loading all icons possible in nuxt.config?

### ISSUE THREAD

**Issue by HenryAveMedi** [bezumkin/nuxt-fontawesome#1]
i'm migrating to nuxt 3, and trying to get my things running, my old fontawesome config alled to do the following

```
fontawesome: {
    icons: {
      regular: true,
      solid: true,
      brands: true
    }
  },
```
That way I didn't have to worry about putting my used icons in 2 places… but this doesn't seems to work in '@vesp/nuxt-fontawesome' is there a way to do this?

**Comment by bezumkin** [comment]
@HenryAveMedi Sorry, this option is not supported in this version. 

There are thousands of icons, and I don't think anyone really needs to use them all.

Therefore you need to explicitly specify which icons you want to use. This way your bundle will be much smaller and will load much faster.

But in return you can specify icon names as they wrote on official website:
```
fontawesome: {
    icons: {
      regular: ['home', 'chevron-up', 'arrow-right'],
```
instead of
```
fontawesome: {
    icons: {
      regular: ['faHome', 'faChevronUp', 'faArrowRight'],
```
